### PR TITLE
Update suggestions on how to get involved

### PR DESCRIPTION
**Pull request by tlycken**
We don't need more issues with people saying "I'm in" - it's time to start working :)

### CODE REVIEW

**Comment by forki** [comment]
@tlycken so it's red for some unrelated reason. But I github does not allow me to merge it

**Comment by tlycken** [comment]
Yeah, I set the master branch to protected to ensure that we don't merge any PR's in the red. We'll have to fix the build before we can merge this (but I guess you're already on it with #55).

**Comment by forki** [comment]
the travis is flaky.

**Comment by forki** [comment]
ok it's green

**Pull request merged**
